import time
print(".")
time.sleep(1)
print(".")
time.sleep(1)
print("Qual o Seu Nome?")
a = input()
print("Certo " + a + " Bem-Vindo(a) Ao  ")
time.sleep(1)
print("Mundo Hacker!!")
time.sleep(1)
print("\n")
print("Ok, agora tenho uma pergunta!")
time.sleep(1)
print("Você já Hackeou antes?, \ S = Sim \ N = Não")
b = input()
if "S" in b:
    print("Ok, isso significa que você é um hacker. Tente isso")
if "N" in b:
    print("Ok você pode usar isso")
time.sleep(1)
print("Ok agora coloque o nome do cliente")
c = input()
print("Coloque o endereço IP de " + c)
d = input()
if len(d) < 5:
    print("Endereço IP Invalido! Execute o programa novamente!")
else:
    print("Checando database de " + c)
    time.sleep(1)
    print("10% de 100")
    time.sleep(2)
    print("50% de 100")
    time.sleep(2)
    print("90% de 100")
    time.sleep(2)
    print("98% de 100")
    time.sleep(4)
    print("100% carregado")
    time.sleep(1)
    print("Vazando informação")
    time.sleep(1)
    print("Encontrado 46 arquivos em database de " + c + "")
    time.sleep(1)
    print("15 raízes encontradas")
    time.sleep(1)
    print("19 arquivos encontrados em data.main")
    time.sleep(1)
    print("copiando informações vazadas para meu banco de dados")
    time.sleep(3)
    print("processo finalizado")
    time.sleep(1)
    print("enviando arquivos da rede de " + c + "")
    time.sleep(3)
    print("processo finalizado")
    time.sleep(1)
    print(a + " os dados foram copiados com sucesso")
    time.sleep(1)
    print("espero que tenha gostado do meu trabalho " + a)
    time.sleep(1)
    print("\n")
